#!/usr/bin/env bash
# gen-vault-rules.sh -- generates .claude/rules/vault/<bucket>-<basename>.md
# stubs from vault note surface/applies_to declarations, and checks whether
# on-disk stubs have drifted from what the vault would generate.
set -u
export LC_ALL=C
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$HERE/vault-lib.sh"
TMP=$(mktemp -d)
trap 'rm -rf "$TMP"' EXIT

usage() {
  echo "usage: gen-vault-rules.sh REPO [--check|--write]" >&2
  exit 2
}

# lint-vault.sh's rules_check() calls this flag-first ("--check REPO"); the
# spec's own CLI is REPO-first ("REPO --check"). Accept both orders so the
# one caller that exists today and the documented CLI both work.
MODE="--check"
REPO=""
for a in "$@"; do
  case "$a" in
    --check|--write) MODE="$a" ;;
    -*) usage ;;
    *) REPO="$a" ;;
  esac
done
[ -n "$REPO" ] && [ -d "$REPO" ] || usage
REPO=$(cd "$REPO" && pwd -P) || usage
VAULT="$REPO/docs/project-knowledge"
RULES="$REPO/.claude/rules/vault"

# --check with no RULES dir means the feature has never been turned on for
# this repo (no --write yet run) -- report nothing rather than flag every
# note as STALE against a directory that was never meant to exist yet.
if [ "$MODE" = "--check" ] && [ ! -d "$RULES" ]; then
  exit 0
fi

vault_merge_schema "$VAULT" "$TMP/schema.json"
vault_records "$VAULT" "$TMP/recs.ndjson"

# Step 1: one row per (note, candidate path), before directory conversion
# (that needs REPO filesystem access, done next in bash). Both surface
# entries and applies_to items go through the same empty/.../PATHRE filter
# and :suffix strip so a garbage applies_to entry can't leak into a stub.
"$JQ" -r "$JQ_FLOW_ITEMS"'
  ($SC[0]) as $sc
  | . as $r
  | ($r.path | split("/")[0]) as $bucket
  | select(($sc.hubs[$r.path] // null) == null)
  | ($r.path | split("/")[-1] | sub("\\.md$"; "")) as $basename
  | (if $bucket == "components" or $bucket == "architecture" then "owns" else "constrains" end) as $kind
  | ($sc.buckets[$bucket].type // $bucket) as $singular
  | (
      [
        (($r.surface.entries // []) | map(.spath)),
        (($r.applies_to // null) | flow_items)
      ]
      | flatten
      | map(select(type == "string" and . != "" and (test("\\.\\.\\.") | not) and (test($PATHRE) or test("^[A-Za-z0-9_.@-]+(/[^ /]+)*/$"))))
      | map(sub(":[^:]*$"; ""))
      | unique
    ) as $paths
  | select(($paths | length) > 0)
  | $paths[] as $p
  | [$bucket, $basename, $kind, $singular, $p]
  | @tsv
' --arg PATHRE "$PATHRE" --slurpfile SC "$TMP/schema.json" "$TMP/recs.ndjson" > "$TMP/raw.tsv"

# Directory conversion: a path ending in "/" or that is a real directory on
# disk becomes a "p/**" glob so the stub covers the whole tree, not just a
# literal file that happens to share the name.
: > "$TMP/converted.tsv"
while IFS="$TAB" read -r bucket basename kind singular p; do
  [ -n "$bucket" ] || continue
  bare="${p%/}"
  if [ "$p" != "$bare" ] || [ -d "$REPO/$bare" ]; then
    conv="$bare/**"
  else
    conv="$p"
  fi
  printf '%s\t%s\t%s\t%s\t%s\n' "$bucket" "$basename" "$kind" "$singular" "$conv" >> "$TMP/converted.tsv"
done < "$TMP/raw.tsv"

sort -t "$TAB" -k1,1 -k2,2 -k5,5 "$TMP/converted.tsv" > "$TMP/converted.sorted.tsv"

# Group consecutive (bucket,basename) rows (input is sorted on that key) into
# one row per note with a deduped, comma-joined path list.
awk -F'\t' '
  function flush() { if (curkey != "") print curbucket, curbasename, curkind, cursingular, joined }
  BEGIN { OFS = "\t"; curkey = "" }
  {
    key = $1 SUBSEP $2
    if (key != curkey) {
      flush()
      curkey = key; curbucket = $1; curbasename = $2; curkind = $3; cursingular = $4
      joined = ""; split("", seen)
    }
    if (!($5 in seen)) { seen[$5] = 1; joined = (joined == "" ? $5 : joined "," $5) }
  }
  END { flush() }
' "$TMP/converted.sorted.tsv" > "$TMP/notes.tsv"

# Step 2: render each stub with printf, LF only. Real newlines inside the
# double-quoted format string (rather than \n escapes) avoid clashing with
# the literal backslash-n a %s substitution could otherwise carry.
mkdir -p "$TMP/gen"
while IFS="$TAB" read -r bucket basename kind singular pathslist; do
  [ -n "$bucket" ] || continue
  yaml=""
  # set -f: the unquoted split must not glob a "d/**" entry against the cwd.
  old_ifs="$IFS"; IFS=","; set -f
  for p in $pathslist; do
    case "$p" in *" "*) p="\"$p\"" ;; esac
    yaml="${yaml:+$yaml, }$p"
  done
  set +f; IFS="$old_ifs"
  fmt="---
paths: [%s]
---
<!-- generated by gen-vault-rules.sh from docs/project-knowledge/%s/%s.md; do not edit -->
Before editing these files, run \`grep -n '^## Reusable surface' docs/project-knowledge/%s/%s.md\` and read that section only; this %s note %s these files.
"
  # "--" stops printf's own option parsing: $fmt starts with "---" (the
  # frontmatter fence), and bash's printf builtin otherwise misparses a
  # leading "-" in FORMAT as a flag instead of literal text.
  printf -- "$fmt" "$yaml" "$bucket" "$basename" "$bucket" "$basename" "$singular" "$kind" > "$TMP/gen/${bucket}-${basename}.md"
done < "$TMP/notes.tsv"

# Step 3 groundwork, shared by --check and the post-write overmatch report:
# one stub<TAB>glob row per declared path, feeding the git-ls-files scan
# that flags a path claimed by more than 3 distinct notes.
: > "$TMP/globs.tsv"
while IFS="$TAB" read -r bucket basename kind singular pathslist; do
  [ -n "$bucket" ] || continue
  stubname="${bucket}-${basename}.md"
  old_ifs="$IFS"; IFS=","; set -f
  for p in $pathslist; do
    printf '%s\t%s\n' "$stubname" "$p" >> "$TMP/globs.tsv"
  done
  set +f; IFS="$old_ifs"
done < "$TMP/notes.tsv"

overmatch_report() {
  if [ -s "$TMP/globs.tsv" ]; then
    git -C "$REPO" ls-files | awk -F'\t' "$AWK_GLOB2ERE"'
      NR == FNR { re[NR] = glob2ere($2); st[NR] = $1; next }
      { c = 0; split("", seen)
        for (i in re) if ($0 ~ re[i] && !seen[st[i]]++) c++
        if (c > 3) print "RULES_FILE_OVERMATCHED\t.claude/rules/vault\t0\t" $0 " matched by " c " notes" }
    ' "$TMP/globs.tsv" -
  fi
}

if [ "$MODE" = "--write" ]; then
  mkdir -p "$RULES"
  for f in "$TMP/gen"/*.md; do
    [ -e "$f" ] || continue
    cp "$f" "$RULES/$(basename "$f")"
  done
  for f in "$RULES"/*.md; do
    [ -e "$f" ] || continue
    name="$(basename "$f")"
    [ -e "$TMP/gen/$name" ] && continue
    grep -qF '<!-- generated by gen-vault-rules.sh' "$f" && rm -f "$f"
  done
  overmatch_report
  exit 0
fi

# --check
: > "$TMP/stale.txt"
: > "$TMP/gennames.txt"
for f in "$TMP/gen"/*.md; do
  [ -e "$f" ] || continue
  name="$(basename "$f")"
  echo "$name" >> "$TMP/gennames.txt"
  cmp -s "$f" "$RULES/$name" 2>/dev/null || echo "STALE .claude/rules/vault/$name" >> "$TMP/stale.txt"
done
sort -o "$TMP/stale.sorted.txt" "$TMP/stale.txt"

: > "$TMP/extra.txt"
if [ -d "$RULES" ]; then
  for f in "$RULES"/*.md; do
    [ -e "$f" ] || continue
    name="$(basename "$f")"
    grep -qxF "$name" "$TMP/gennames.txt" && continue
    grep -qF '<!-- generated by gen-vault-rules.sh' "$f" && echo "EXTRA .claude/rules/vault/$name" >> "$TMP/extra.txt"
  done
fi
sort -o "$TMP/extra.sorted.txt" "$TMP/extra.txt"

cat "$TMP/stale.sorted.txt" "$TMP/extra.sorted.txt"
overmatch_report

if [ -s "$TMP/stale.sorted.txt" ] || [ -s "$TMP/extra.sorted.txt" ]; then
  exit 1
fi
exit 0
